# Generated by Django 2.1.1 on 2018-09-25 17:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 25, 17, 2, 17, 698458, tzinfo=utc), editable=False, verbose_name='Data de Criação'),
        ),
    ]
