# Generated by Django 2.1.1 on 2018-09-25 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_auto_20180925_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='creation_date',
            field=models.DateTimeField(default='2018-09-25T17:17:36.937735+00:00', editable=False, verbose_name='Data de Criação'),
        ),
    ]
