# Generated by Django 2.1.1 on 2018-09-25 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_auto_20180925_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='creation_date',
            field=models.DateTimeField(default='2018-09-25T18:33:22.752347+00:00', editable=False, verbose_name='Data de Criação'),
        ),
    ]
